# BUILD Settings:
# ##############################################################################
[build]
  command = "npm run build"
  publish = ".next"

[dev]
  publish = ".next"
  port = 64946
  autolaunch = true

# PLUGINS
# ##############################################################################
[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-vault-variables"
  [plugins.inputs]
    endpoint = 'https://vault.stanford.edu'
    # Order doesn't matter here as these will be fetch asyncronously. Try not to have dupes.
    secrets = ['secret/data/projects/adapt/stripe', 'secret/data/projects/adapt/saml']
    # Set which environment variables to use for the approle login
    secretId = 'VAULT_SECRET_ID'
    roleId = 'VAULT_ROLE_ID'

# HEADERS - BASIC AUTH
# ##############################################################################
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "form-action https:"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Strict-Transport-Security = "max-age=2592000"
    Permissions-Policy = "vibrate=(), geolocation=(), midi=(), notifications=(), push=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), speaker=()"
    X-Robots-Tag = "noindex, nofollow"
    X-Frame-Options = "DENY"